# Generated by Django 4.1 on 2024-03-02 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, null=True)),
                ('description', models.TextField(null=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
